# Generated by Sharpmake -- Do not edit !
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  CXX        = clang++
  AR         = ar
  OBJDIR     = obj/linux/Debug
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/textured
  DEFINES   += -D "_DEBUG"
  INCLUDES  += -I../../dependencies/abseil-cpp -I../../dependencies/cereal -I../../dependencies/eigen -I../../dependencies/eve -I../../dependencies/fast_float -I../../dependencies/fast_obj -I../../dependencies/gli -I../../dependencies/glm -I../../dependencies/imgui -I../../dependencies/Remotery -I../../dependencies/stb -I../../dependencies/tinyclock/Include -I../../dependencies/tinyextender/Include -I../../dependencies/tinyshaders/Include -I../../dependencies/tinywindow/Dependencies -I../../dependencies/tinywindow/Include -I../../include -I../Scene/include -Iinclude
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) -g -Wall 
  CXXFLAGS  += $(CFLAGS) -std=c++2a -fno-exceptions -fno-rtti 
  LDFLAGS   +=  -lGL -lX11
  LDLIBS    +=  
  RESFLAGS  += $(DEFINES) $(INCLUDES)
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(LDLIBS)
  PCH        = 
  PCHOUT     = 
  GCH        = 
  PCHCMD     = 
  define PREBUILDCMDS
    
  endef
  define PRELINKCMDS
    
  endef
  define POSTBUILDCMDS
    
  endef
  define POSTFILECMDS
  endef
endif

ifeq ($(config),release)
  CXX        = clang++
  AR         = ar
  OBJDIR     = obj/linux/Release
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/textured
  DEFINES   += -D "NDEBUG"
  INCLUDES  += -I../../dependencies/abseil-cpp -I../../dependencies/cereal -I../../dependencies/eigen -I../../dependencies/eve -I../../dependencies/fast_float -I../../dependencies/fast_obj -I../../dependencies/gli -I../../dependencies/glm -I../../dependencies/imgui -I../../dependencies/Remotery -I../../dependencies/stb -I../../dependencies/tinyclock/Include -I../../dependencies/tinyextender/Include -I../../dependencies/tinyshaders/Include -I../../dependencies/tinywindow/Dependencies -I../../dependencies/tinywindow/Include -I../../include -I../Scene/include -Iinclude
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) -g -O3 -Wall 
  CXXFLAGS  += $(CFLAGS) -std=c++2a -fno-exceptions -fno-rtti 
  LDFLAGS   +=  -lGL -lX11
  LDLIBS    +=  
  RESFLAGS  += $(DEFINES) $(INCLUDES)
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(LDLIBS)
  PCH        = 
  PCHOUT     = 
  GCH        = 
  PCHCMD     = 
  define PREBUILDCMDS
    
  endef
  define PRELINKCMDS
    
  endef
  define POSTBUILDCMDS
    
  endef
  define POSTFILECMDS
  endef
endif

ifeq ($(config),debug)
  OBJECTS += $(OBJDIR)/imgui.o
  OBJECTS += $(OBJDIR)/ImGuizmo.o
  OBJECTS += $(OBJDIR)/imgui_demo.o
  OBJECTS += $(OBJDIR)/imgui_draw.o
  OBJECTS += $(OBJDIR)/imgui_tables.o
  OBJECTS += $(OBJDIR)/imgui_widgets.o
  OBJECTS += $(OBJDIR)/Textured3.o
endif

ifeq ($(config),release)
  OBJECTS += $(OBJDIR)/imgui.o
  OBJECTS += $(OBJDIR)/ImGuizmo.o
  OBJECTS += $(OBJDIR)/imgui_demo.o
  OBJECTS += $(OBJDIR)/imgui_draw.o
  OBJECTS += $(OBJDIR)/imgui_tables.o
  OBJECTS += $(OBJDIR)/imgui_widgets.o
  OBJECTS += $(OBJDIR)/Textured3.o
endif

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking Textured
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) if not exist $(subst /,\\,$(TARGETDIR)) mkdir $(subst /,\\,$(TARGETDIR))
endif

ifneq ($(OBJDIR),$(TARGETDIR))
$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) if not exist $(subst /,\\,$(OBJDIR)) mkdir $(subst /,\\,$(OBJDIR))
endif
endif

clean:
	@echo Cleaning Textured
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -xc++-header -o "$@" -c "$<"
	$(SILENT) $(POSTFILECMDS)
endif

$(OBJDIR)/imgui.o: ../../dependencies/imgui/imgui.cpp $(GCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) $(PCHCMD) -o "$@" -c "$<"
	$(SILENT) $(POSTFILECMDS)

$(OBJDIR)/ImGuizmo.o: ../../dependencies/imgui/ImGuizmo.cpp $(GCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) $(PCHCMD) -o "$@" -c "$<"
	$(SILENT) $(POSTFILECMDS)

$(OBJDIR)/imgui_demo.o: ../../dependencies/imgui/imgui_demo.cpp $(GCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) $(PCHCMD) -o "$@" -c "$<"
	$(SILENT) $(POSTFILECMDS)

$(OBJDIR)/imgui_draw.o: ../../dependencies/imgui/imgui_draw.cpp $(GCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) $(PCHCMD) -o "$@" -c "$<"
	$(SILENT) $(POSTFILECMDS)

$(OBJDIR)/imgui_tables.o: ../../dependencies/imgui/imgui_tables.cpp $(GCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) $(PCHCMD) -o "$@" -c "$<"
	$(SILENT) $(POSTFILECMDS)

$(OBJDIR)/imgui_widgets.o: ../../dependencies/imgui/imgui_widgets.cpp $(GCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) $(PCHCMD) -o "$@" -c "$<"
	$(SILENT) $(POSTFILECMDS)

$(OBJDIR)/Textured3.o: source/Textured.cpp $(GCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) $(PCHCMD) -o "$@" -c "$<"
	$(SILENT) $(POSTFILECMDS)

-include $(OBJECTS:%.o=%.d)
-include $(GCH:%.gch=%.d)
